### ISSUE TITLE
LinkKit for Catalyst/UIKitForMac

### ISSUE THREAD

**Issue by jayrhynas** [Ableton/LinkKit#52]
Are there any plans to release a compiled version of LinkKit that's compatible with the UIKitForMac platform?

#### Background:

At WWDC 2019, Apple announced Catalyst, a new way to compile iPad apps and run them on the Mac. This was previously announced under the code name Marzipan in 2018.

Most iOS dependencies provided as source work fine with Catalyst. Xcode happily re-compiles them for the "UIKitForMac" platform. However, since LinkKit is distributed as a binary-only framework, Catalyst apps can't link against it.

**Comment by Cclleemm** [comment]
+1 @jayrhynas hope it will release soon :)

**Comment by fgo-ableton** [comment]
Thanks for asking. Here's a test version of LinkKit containing a xcframework that works with UIKit for Mac: [LinkKit_uikitformac_test.zip](https://github.com/Ableton/LinkKit/files/3427187/LinkKit_uikitformac_test.zip) Let me know if that works for you.
This breaks compatibility with Xcode versions older than 11, so we'll probably have a fat lib and a xcframework in the next release. We'll wait until Catalyst is out of beta with that.
Anyways, feel free to use this or build LinkKit from source for testing in the meantime.

**Comment by fgo-ableton** [comment]
I just uploaded a beta with Catalyst support: https://github.com/Ableton/LinkKit/releases/tag/LinkKit-3.1.0-Beta

**Comment by uwehollatz** [comment]
Is there a plan/timeline to publish a release of 3.1.0 or at least a release candidate?

**Comment by fgo-ableton** [comment]
@uwehollatz Here's a new release: https://github.com/Ableton/LinkKit/releases/tag/LinkKit-3.1.0
I still marked it a pre-release, because only I have tested it. If you (or someone else) could confirm it's working as expected, I'll remove the pre-release tag.

**Comment by uwehollatz** [comment]
OK cool, I will do the testing and report back to you, thanks much!

**Comment by uwehollatz** [comment]
I have tested and I can confirm that the pre-release 3.1.0 is working as expected. Brilliant.

Two side notes:
- Localization: The view controllers are not localized, any plan to do so? I can probably contribute if desired.
- Support for Scenes on iPad OS: When using UISceneDelegate, the In-App Notification do not show up. Is there a plan that LinkKit will support Scenes, a new feature for iPadOS 13.1 which enables windows support on iPads?

May be its worth to create new issues to track that separately?

**Comment by fgo-ableton** [comment]
Thanks for testing! I'll remove the pre-release tag then.

Regarding the other points: Yes, please open new issues.

**Comment by alessandropetrolati** [comment]
Hello,
the libABLLink.a form the LinkKit-3.1.0 (beta and release)
does not works anymore in the simulator, this is because the simulator need to be compiled either as i386.

If you use the limo command

lipo -info libABLLink.a

you will see in the 3.1.o only armv7 arm64 and x86_64 supported architectures.
In the previous version (3.0.5) also i386 is supported.
In the same way, the .xcframework ios-x86_64-simulator should contains either x86_64 and i386

Thanks, cheers.


----------------------------
Alessandro Petrolati
Loc. Acquaviva, 33
61043 Cagli/PU
Italy

www.apesoft.it <http://www.apesoft.it/>
info@apesoft.it
apps@apesoft.it <mailto:info@alessandro-petrolati.it>
----------------------------

**Comment by uwehollatz** [comment]
@alessandropetrolati LinkKit 3.1.0 is 64bit only. i386 is build for 32bit processor family and removed since that version. And, of course it's running in simulator. Please update your build platform.

**Comment by alessandropetrolati** [comment]
I got this error for iOS Simulator-x86_64

ld: warning: ignoring file /Users/io/Library/Developer/Xcode/DerivedData/apeMatrix-gyabcjbqbqongxffolkgwisnaili/Build/Products/Release-iphonesimulator/libLinkKit.a, building for iOS Simulator-i386 but attempting to link with file built for iOS Simulator-x86_64
Undefined symbols for architecture i386:
  "_ABLLinkCaptureAppSessionState", referenced from:
      -[APE_SYNC bpm] in APE_SYNC.o
  "_ABLLinkNew", referenced from:
      -[APE_SYNC initLinkData:] in APE_SYNC.o
  "_ABLLinkSetSessionTempoCallback", referenced from:
      -[APE_SYNC initLinkData:] in APE_SYNC.o
  "_ABLLinkSetIsEnabledCallback", referenced from:
      -[APE_SYNC initLinkData:] in APE_SYNC.o
  "_ABLLinkIsEnabled", referenced from:
      -[APE_SYNC initLinkData:] in APE_SYNC.o
      -[APE_SYNC isConnectedFromABL] in APE_SYNC.o
      -[APE_SYNC isLinkEnabled] in APE_SYNC.o
  "_ABLLinkGetTempo", referenced from:
      -[APE_SYNC setIsPlaying:] in APE_SYNC.o
      -[APE_SYNC bpm] in APE_SYNC.o
      -[APE_SYNC startSendClock] in APE_SYNC.o
  "_ABLLinkDelete", referenced from:
      -[APE_SYNC dealloc] in APE_SYNC.o
  "_ABLLinkIsPlaying", referenced from:
      abletonLinkComputeBeatFromAudio(APE_SYNC*, unsigned long*, AudioTimeStamp const*, unsigned long, unsigned long, AudioBufferList*, HostCallbackInfo*) in APE_SYNC.o
  "_ABLLinkCaptureAudioSessionState", referenced from:
      abletonLinkComputeBeatFromAudio(APE_SYNC*, unsigned long*, AudioTimeStamp const*, unsigned long, unsigned long, AudioBufferList*, HostCallbackInfo*) in APE_SYNC.o
      renderMetronomeIntoBuffer(APE_SYNC*, AudioTimeStamp const*, unsigned long, AudioBufferList*, float, int, int) in APE_SYNC.o
      -[APE_SYNC setIsPlaying:] in APE_SYNC.o
      -[APE_SYNC startSendClock] in APE_SYNC.o
  "_ABLLinkSetIsPlaying", referenced from:
      abletonLinkComputeBeatFromAudio(APE_SYNC*, unsigned long*, AudioTimeStamp const*, unsigned long, unsigned long, AudioBufferList*, HostCallbackInfo*) in APE_SYNC.o
  "_OBJC_CLASS_$_ABLLinkSettingsViewController", referenced from:
      objc-class-ref in APE_SYNC.o
  "_ABLLinkRequestBeatAtStartPlayingTime", referenced from:
      abletonLinkComputeBeatFromAudio(APE_SYNC*, unsigned long*, AudioTimeStamp const*, unsigned long, unsigned long, AudioBufferList*, HostCallbackInfo*) in APE_SYNC.o
  "_ABLLinkCommitAudioSessionState", referenced from:
      abletonLinkComputeBeatFromAudio(APE_SYNC*, unsigned long*, AudioTimeStamp const*, unsigned long, unsigned long, AudioBufferList*, HostCallbackInfo*) in APE_SYNC.o
  "_ABLLinkRequestBeatAtTime", referenced from:
      abletonLinkComputeBeatFromAudio(APE_SYNC*, unsigned long*, AudioTimeStamp const*, unsigned long, unsigned long, AudioBufferList*, HostCallbackInfo*) in APE_SYNC.o
  "_ABLLinkSetStartStopCallback", referenced from:
      -[APE_SYNC initLinkData:] in APE_SYNC.o
  "_ABLLinkPhaseAtTime", referenced from:
      abletonLinkComputeBeatFromAudio(APE_SYNC*, unsigned long*, AudioTimeStamp const*, unsigned long, unsigned long, AudioBufferList*, HostCallbackInfo*) in APE_SYNC.o
      renderMetronomeIntoBuffer(APE_SYNC*, AudioTimeStamp const*, unsigned long, AudioBufferList*, float, int, int) in APE_SYNC.o
  "_ABLLinkSetTempo", referenced from:
      abletonLinkComputeBeatFromAudio(APE_SYNC*, unsigned long*, AudioTimeStamp const*, unsigned long, unsigned long, AudioBufferList*, HostCallbackInfo*) in APE_SYNC.o
  "_ABLLinkBeatAtTime", referenced from:
      abletonLinkComputeBeatFromAudio(APE_SYNC*, unsigned long*, AudioTimeStamp const*, unsigned long, unsigned long, AudioBufferList*, HostCallbackInfo*) in APE_SYNC.o
      renderMetronomeIntoBuffer(APE_SYNC*, AudioTimeStamp const*, unsigned long, AudioBufferList*, float, int, int) in APE_SYNC.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by uwehollatz** [comment]
Please make sure you have updated your build settings, remove any i386 reference: here is mine as an example:

https://www.dropbox.com/s/6fsa0a9pinyal07/Screenshot%202020-02-29%2016.09.15.png?dl=0

**Comment by alessandropetrolati** [comment]
I’ve exactly this configuration but still not works,
very confused!
I’m compiling in Objective-C++.
Thanks.

**Comment by fgo-ableton** [comment]
@alessandropetrolati As @uwehollatz stated above, we had to drop support for that architecture in the latest release. The log you pasted above says `building for iOS Simulator-i386` which indicates Xcode is trying to build for that architecture. If you can't find the corresponding section in the Xcode settings, maybe try to set up a new Xcode project. Also, we added an `.xcodebundle` to the release which should adding LinkKit to a Xcode 11 project easier.
Objective-C++ shouldn't be a problem, it is used in LinkKit as well.

**Comment by cerupcat** [comment]
I'm able to compile the latest version of LinkKit (with Catalyst) in Debug, but not in Release / Archive. The following error occurs both in my own project and the LinkHut example project when trying to build / archive. It builds fine in debug since `Build For Active Architecture` is `YES`, but not in release; therefore, there's no way to submit to the AppStore.

![Screen Shot 2020-09-04 at 3 52 47 PM](https://user-images.githubusercontent.com/204151/92289843-d7d1af00-eec6-11ea-80f1-18a46d31eb5b.png)

**Comment by fgo-ableton** [comment]
@cerupcat 
[Here's](https://github.com/Ableton/LinkKit/files/5183481/LinkKit.zip) a build made with Xcode 12 beta 6. Could you check if that works for you?

**Comment by jnpdx** [comment]
@fgo-ableton That build worked for me when I was encountering the same issue (on Xcode 12.2 -- release version).  Thank you.

**Comment by fgo-ableton** [comment]
Hey all, [here's](https://github.com/Ableton/LinkKit/releases/tag/LinkKit-3.1.4) a pre-release with support for Apple Silicon. It would be great if someone could give it a sanity check.
