### ISSUE TITLE
Localization Support

### ISSUE THREAD

**Issue by uwehollatz** [Ableton/LinkKit#53]
The view controllers of LinkKit are not localized. Please add standard localization so it can be extended by Localization strings files.

**Comment by fgo-ableton** [comment]
Here's a pre-release with localization support: https://github.com/Ableton/LinkKit/releases/tag/LinkKit-3.1.1
It would be great if you could give it a try.

**Comment by uwehollatz** [comment]
Brillant - I will try that out next few days and let you know here, thanks much.

**Comment by uwehollatz** [comment]
OK, I have tested all languages, and it works perfect :)
[localizations.zip](https://github.com/Ableton/LinkKit/files/4603565/localizations.zip)
 I have added Russian, and done small correction for German, please review:

**Comment by fgo-ableton** [comment]
Thanks for testing! I'll remove the pre-release flag then.

Also thanks for sending the .zip. Regarding the changes in the german version, we'll stick with the current version. Using Peers makes more sense as this can refer to Apps as well as devices.
Do you think the russian translation still makes sense in that regard?
Also, please sign a CLA to give us legal permission use your contribution: https://ableton.github.io/cla/

**Comment by uwehollatz** [comment]
Ok, I have signed the CLA.
About Russian translation: I have talked with native speaker, but in context of Application or Device instead of Peer. The pure translation Peer would be Коллега, but this is more for human individuals. IMHO I would go for другие устройства, is seems to be clear at least for my translator :)

**Comment by fgo-ableton** [comment]
Thanks a lot. Here's a new release: https://github.com/Ableton/LinkKit/releases/tag/LinkKit-3.1.2
Please give it a try.

**Comment by uwehollatz** [comment]
Works perfect, thanks much!
We can close the thread now :)
