### ISSUE TITLE
Support for Scenes on iPad OS

### ISSUE THREAD

**Issue by uwehollatz** [Ableton/LinkKit#54]
Symptom: When using UISceneDelegate, the In-App Notification do not show up.
Please add support for UISceneDelegate, a new feature for iPadOS 13.1 which enables windows support on iPads.

**Comment by fgo-ableton** [comment]
This took a while... but here's build that should fix the issue. Could you check if it works for you?
[LinkKit.zip](https://github.com/Ableton/LinkKit/files/4770982/LinkKit.zip)

**Comment by uwehollatz** [comment]
Thanks much, I will try that out and let you know.

**Comment by uwehollatz** [comment]
OK, I've tested and its working for me, thanks much!
