### ISSUE TITLE
[3.1.0] Tempo callback not called if new tempo matches old tempo

### ISSUE THREAD

**Issue by tehpsy** [Ableton/LinkKit#55]
After setting up link:
`_linkRef = ABLLinkNew (120);`

Then changing the tempo:
`ABLLinkSetTempo (..., 120, ...);`

The tempo callback (defined `ABLLinkSetSessionTempoCallback`) is not called.

When the tempo is set to anything other than 120, the callback is called correctly.
Not that this was not the case in Link 2.x -- the tempo change callback would always be called.

Is this intentional behaviour? It is surprising!

**Comment by fgo-ableton** [comment]
Yes, this is intended behavior.
So when i.e. creating the object that should listen to the tempo, one would:
* Create the object
* Register the callback
* Use the `ABLLinkGetSessionTempo()` to set the initial tempo of the object
After that the object is updated from the callback every time the tempo (actually) changes.

**Comment by tehpsy** [comment]
Thanks for your response!
