### ISSUE TITLE
ARM Mac - Cannot link when building with LinkKit to target (ARM based...) iOS Emulator

### ISSUE THREAD

**Issue by sseyod** [Ableton/LinkKit#60]
Hi!

As the title says: when building using ARM-based Mac, it is not possible to link with LinkKit when targeting the iOS Emulator.

The reason is that on ARM Macs, the Simulator requires ARM code; as opposed to Intel Macs, where the Simulator requires x86 code, and LinkKit can be compiled-in successfully.

In case it helps, you can look at the latest version of the Audiobus SDK, where they've updated to solve this problem for Audiobus developers.

Thanks in advance, Pete

**Comment by fgo-ableton** [comment]
Are you trying to link the `.a` or the `.xcframework`? The `.xcframework` should contain symbols for ARM. But I have not been able to test it on an actual ARM machine yet.

**Comment by sseyod** [comment]
Hi! Using on an Apple Silicon Mac, using the .xcframework you provide. I hope that helps!

Best wishes, Pete

**Comment by cdi-ableton** [comment]
Could you please test building LinkHut? I'm able to build it targeting the Simulator on an M1 Macbook Air using LinkKit 3.1.5 and Xcode 12.3.

**Comment by sseyod** [comment]
HI! Yes, of course, I'll try that out for you. Just been maxed-out getting a release together for past couple of days!

NB: can I please ask you to double-check that your framework is set-up correctly for bitcode, before I try this?

Technical background is here:
https://stackoverflow.com/questions/58740662/does-bitcode-support-weak-linking-third-party-frameworks

... as I yesterday saw that problem in another 3rd party library the was trying to use a xcframework for iOS...

Best wishes, Pete

**Comment by sseyod** [comment]
Hi! Now that I *finally* have an M1 mac, I'm finding that:

1) if I build using libABLLink.a, I cannot build and run on the Simulator, seeing this error:

"building for iOS Simulator, but linking in object file built for iOS, file '........./libABLLink.a' for architecture arm64

2) if I build using the Framework, this runs on the Simulator, but I cannot **export an archive** built to target the generic iOS app **to IPA file** for AdHoc distribution

My only work-around for now would be:
- for everyday testing, use the Framework
- for archive builds, modify my projects to remove the Framework, and switch to the libABLLink.a
Unfortunately, there is no way I can see in Xcode to achieve this without manually altering the project when it comes to building for archive.

Can you please fix this ASAP.

**Comment by sseyod** [comment]
Hi @fgo-ableton I can't see how to re-open this issue :)

Best wishes, Pete

**Comment by sseyod** [comment]
Furthermore, I'm prevented from enabling bitcode for my project, as the Ableton library for iOS isn't build to include bitcode.

**Comment by sseyod** [comment]
NB: my code is built such the the App and Audio engine are separated, with my audio engine in a private framework.
It is the private framework that uses LinkKit - and I can only link with static libraries from my Framework, as my Framework is used in an App Extension (the AUv3 version of my app).

So, I really require a fix from you for the libABLLink.a problem reported above.

Best wishes, Pete

**Comment by fgo-ableton** [comment]
Hey @sseyod,
Could you check out [this build](https://ci.appveyor.com/api/buildjobs/tk94r17vkdyvv7si/artifacts/build%2Foutput%2FLinkKit.zip)? 
It is built with Xcode 13 so it should support Apple Silicon. 
I just tried archiving the example app for both: Any iOS Device and Any Mac and it worked. Bitcode is enabled.
You should be able to use for the .xcframework for all targets. The .a is mostly in there for backwards compatibility, it doesn't support all architectures.

**Comment by sseyod** [comment]
Hi @fgo-ableton, I'll be happy to try that out for you later this morning, and will report back.

However - to be 100% clear, I require a working .a file implementation, because the LInkKit library in my system needs to be built-in to a private framework. NB this is the exact approach I'm using with AudioBus SDK library, where they're clearly building the static .a file differently to the way that you've been doing!

Best wishes, Pete

**Comment by sseyod** [comment]
@fgo-ableton on first test, that now allows me to build and run on Simulator from M1 Mac, which is great progress, thank you.

**Comment by sseyod** [comment]
NB that was using the Framework version of LinkKit

**Comment by sseyod** [comment]
@fgo-ableton if I try to **export the archive** to .iap file, I get the same problem as previously reported

<img width="318" alt="image" src="https://user-images.githubusercontent.com/2429049/144814982-569945e2-876c-4229-b15b-540766a77fca.png">

**Comment by sseyod** [comment]
From the logs:

[OPTIONAL] Didn't find platform (null) or cert (null) for <DVTFilePath:0x3811bb3f0:'/Users/pcole/Library/Developer/Xcode/Archives/2021-12-06/Wotja_iOS_Pro_App 06-12-2021, 08.44.xcarchive/Products/Applications/Wotja 22 Pro.app/Frameworks/ISSKit.framework/Frameworks/libLinkKit.a'>: Error Domain=DVTFoundationNSBundleAdditionsErrorDomain Code=1 "Couldn't find platform family for "libLinkKit.a"." UserInfo={NSLocalizedDescription=Couldn't find platform family for "libLinkKit.a"., NSLocalizedRecoverySuggestion=Couldn't find CFBundleSupportedPlatforms in the Info.plist, LC_VERSION_MIN, or LC_BUILD_VERSION in the Mach-O for path "/Users/pcole/Library/Developer/Xcode/Archives/2021-12-06/Wotja_iOS_Pro_App 06-12-2021, 08.44.xcarchive/Products/Applications/Wotja 22 Pro.app/Frameworks/ISSKit.framework/Frameworks/libLinkKit.a".}

**Comment by sseyod** [comment]
@fgo-ableton I'm optimistic that from the above info, you might be able to figure-out the problem. Hoping this helps, Pete

**Comment by sseyod** [comment]
@fgo-ableton just to further report, I've tried using the static library in what you've given me, and still get this:

libABLLink.a(ABLNotificationView.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/..../libABLLink.a' for architecture arm64

To be 100% clear, if you can fix the static library, then I think that will clear all of my problems.

**Comment by fgo-ableton** [comment]
Hmm, I am still not clear on what the issue is. I compared the supported architectures with what audiobus supports. It looks pretty similar:
```
libABLLink.a: Mach-O universal binary with 4 architectures: [arm64:current ar archive] [arm_v7] [x86_64] [i386]
libABLLink.a (for architecture arm64):  current ar archive
libABLLink.a (for architecture armv7):  current ar archive
libABLLink.a (for architecture x86_64): current ar archive
libABLLink.a (for architecture i386):   current ar archive

libAudiobus.a: Mach-O universal binary with 4 architectures: [i386:current ar archive] [arm_v7] [x86_64] [arm64]
libAudiobus.a (for architecture i386):   current ar archive
libAudiobus.a (for architecture armv7):  current ar archive
libAudiobus.a (for architecture x86_64): current ar archive
libAudiobus.a (for architecture arm64):  current ar archive
```

Also the `.xcarchive` and the `.a` versions of LinkKit are pretty much the same. The `.xcarchive` additionally supports Catalyst. But both use the exact same symbols for iphoneos and iphonesimulator. https://github.com/Ableton/LinkKit/blob/1b21fe7b400774353844e875af52553c45c9adcc/makefile#L43
So regarding linking the `.a` vs the `.xcframework`, I don't understand why you need to link to the `.a`. According to [this article](https://medium.com/john-lewis-software-engineering/adding-a-third-party-framework-inside-a-first-party-framework-in-xcode-3ba58cfd08da) linking a framework from another framework should be possible.

It would be good to know if you can reproduce the issue with the LinkHut example app! Maybe that gives a lead.

**Comment by sseyod** [comment]
@fgo-ableton Hi - sorry, I've made a dumb mistake earlier

**Comment by sseyod** [comment]
I'd accidentally reverted your updated LinkKit.zip file changes, before building for archive an .iap export (!)

The build and iap export is working fine now, using the framework.

**Comment by sseyod** [comment]
@fgo-ableton so, sorry about that.

However, the zip file you made available for testing looks as though it might be missing a couple of folders? Just to show what I mean in this screen shot:
<img width="502" alt="image" src="https://user-images.githubusercontent.com/2429049/144844106-0d992324-f794-47df-ba2e-1edb59b1612e.png">

**Comment by sseyod** [comment]
@fgo-ableton so, sorry about that!!

**Comment by fgo-ableton** [comment]
@sseyod No worries! Glad it is resolved. 😄

**Comment by sseyod** [comment]
Thank you very much @fgo-ableton 😄 

Best wishes, Pete
