### ISSUE TITLE
Crashes in ABLLinkNew() on older iPad

### ISSUE THREAD

**Issue by lijon** [Ableton/LinkKit#66]
After updating to latest LinkKit 3.1.8, it crashes with SIGABRT on `ABLLinkNew(tempo)` when running on my old test device: an iPad Mini 2, A7 CPU running iOS 12.5.5. It works fine with LinkKit 3.1.7.

I noticed that 3.1.8 dropped armv7 support, but not sure that's related since A7 is armv8 (64 bit).

**Comment by fgo-ableton** [comment]
It seems I accidentally changed the deployment target in https://github.com/Ableton/LinkKit/commit/df0d09b4a6a701081542db4afa7124653cceac6a
Could you check if [this](https://github.com/Ableton/LinkKit/files/8521719/LinkKit.zip) build works for you?

**Comment by lijon** [comment]
Yes, that build works. Thank you!

**Comment by mazbox** [comment]
Had same problem, this fixed it thanks!!

**Comment by fgo-ableton** [comment]
Thanks for testing! I published a new release: https://github.com/Ableton/LinkKit/releases/tag/LinkKit-3.1.9
