### ISSUE TITLE
Update to Xcode 14 new error: libABLLink.a building for iOS, but linking in object file built for iOS Simulator ..."architecture arm64"

### ISSUE THREAD

**Issue by luismartimor** [Ableton/LinkKit#68]
Just updated to Xcode 14 and getting a new error  testing on real devices (iPad or iPhone), no issues with Xcode 13:
  
" error build: In …/ABLink/libABLLink.a(ABLLink.o), building for iOS, but linking in object file built for iOS Simulator, file ‘…/ABLink/libABLLink.a' for architecture arm64 "

It works on the simulator

**Comment by fgo-ableton** [comment]
Please use the `.xcframework` from the latest release. The fat library is not supported anymore. See https://github.com/Ableton/LinkKit/issues/67
